schema_version = 1
fcbc_version = "2.0.0"
execution_abi_version = "1.0.0"
source_fcs_version = "5.0.0"
container_profile = "runtime"
document_profile = "fragment"
path = "minimal-runtime.hex"
decoded_length = 804
sha256 = "461b6bf2a1cf5e99ad0e81fb01d4621f149dd0a54f8eff403bf4924dda837f6c"

[[section]]
type = 1
name = "StringTable"
offset = 648
length = 8
crc32 = "6522df69"

[[section]]
type = 2
name = "ConstantPool"
offset = 656
length = 4
crc32 = "2144df1c"
[[section]]
type = 3
name = "Meta"
offset = 664
length = 24
crc32 = "016062d3"

[[section]]
type = 4
name = "Contributors"
offset = 688
length = 4
crc32 = "2144df1c"

[[section]]
type = 5
name = "Credits"
offset = 696
length = 4
crc32 = "2144df1c"

[[section]]
type = 6
name = "Resources"
offset = 704
length = 4
crc32 = "2144df1c"

[[section]]
type = 7
name = "Sync"
offset = 712
length = 48
crc32 = "6ea5c831"

[[section]]
type = 8
name = "TempoMap"
offset = 760
length = 4
crc32 = "2144df1c"

[[section]]
type = 9
name = "Lines"
offset = 768
length = 4
crc32 = "2144df1c"

[[section]]
type = 10
name = "Notes"
offset = 776
length = 4
crc32 = "2144df1c"

[[section]]
type = 11
name = "Tracks"
offset = 784
length = 4
crc32 = "2144df1c"

[[section]]
type = 12
name = "Expressions"
offset = 792
length = 4
crc32 = "2144df1c"

[[section]]
type = 13
name = "Distance"
offset = 800
length = 4
crc32 = "2144df1c"
