#!/usr/bin/env python3
"""Materialize per-target fuzz seed corpora from checked-in evidence.

Usage: fcs5-fuzz-seeds.py <repo_root> <dest_root> [target ...]

Seeds come only from files the repository already binds as evidence, so the
fuzz corpus cannot silently drift from the conformance manifests:

- FCS source targets: every fixture in ``docs/conformance/fcs5/manifest.toml``
  plus the public ``examples/fcs/*.fcs`` inputs;
- FCBC/Render targets: the checked-in container goldens, hex-decoded;
- importer targets: the public conversion fixture sources;
- ``asset_image``: one generated minimal PNG (no image evidence is checked
  in), prefixed with the target's parameter-selector byte;
- ``asset_font``: no seeds (the project font is generated by Rust code and a
  whole-file checksum makes mutated copies worthless as seeds).

Every requested target directory is created even when it stays empty.
Existing destination files are never overwritten or deleted, so a
coverage-grown corpus restored from cache keeps its inputs.
"""

import shutil
import struct
import sys
import tomllib
import zlib
from pathlib import Path


def place(destination: Path, name: str, data: bytes) -> None:
    path = destination / name
    if not path.exists():
        path.write_bytes(data)


def copy(destination: Path, name: str, source: Path) -> None:
    path = destination / name
    if not path.exists():
        shutil.copyfile(source, path)


def seed_fcs_source(root: Path, destination: Path) -> None:
    manifest_path = root / "docs" / "conformance" / "fcs5" / "manifest.toml"
    manifest = tomllib.loads(manifest_path.read_text())
    for fixture in manifest["fixture"]:
        source = manifest_path.parent / fixture["path"]
        copy(destination, fixture["id"].replace("/", "_") + ".fcs", source)
    for source in sorted((root / "examples" / "fcs").glob("*.fcs")):
        copy(destination, "example-" + source.name, source)


def seed_fcbc_goldens(root: Path, destination: Path) -> None:
    for source in sorted((root / "docs" / "conformance" / "fcbc").glob("*.hex")):
        data = bytes.fromhex("".join(source.read_text().split()))
        place(destination, source.stem + ".bin", data)


def seed_conversion_sources(root: Path, destination: Path, suffix: str) -> None:
    sources = root / "docs" / "conformance" / "conversion" / "public-fixtures" / "sources"
    for source in sorted(sources.glob("*" + suffix)):
        copy(destination, source.name, source)


def minimal_png() -> bytes:
    def chunk(kind: bytes, payload: bytes) -> bytes:
        raw = kind + payload
        return struct.pack(">I", len(payload)) + raw + struct.pack(">I", zlib.crc32(raw))

    header = struct.pack(">IIBBBBB", 2, 2, 8, 6, 0, 0, 0)  # 2x2 RGBA8
    scanlines = b"".join(b"\x00" + bytes(8) for _ in range(2))
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(scanlines))
        + chunk(b"IEND", b"")
    )


def seed_asset_image(_root: Path, destination: Path) -> None:
    # Selector byte 0x00 = image/png, srgb, straight (see asset_image.rs).
    place(destination, "selector-png.bin", b"\x00" + minimal_png())


def seed_nothing(_root: Path, _destination: Path) -> None:
    pass


SEEDERS = {
    "document_bytes": seed_fcs_source,
    "document_utf8": seed_fcs_source,
    "expression": seed_fcs_source,
    "fcbc_container": seed_fcbc_goldens,
    "render_section": seed_fcbc_goldens,
    "asset_image": seed_asset_image,
    "asset_font": seed_nothing,
    "import_pgr": lambda root, dest: seed_conversion_sources(root, dest, ".pgr.json"),
    "import_rpe": lambda root, dest: seed_conversion_sources(root, dest, ".rpe.json"),
    "import_pec": lambda root, dest: seed_conversion_sources(root, dest, ".pec"),
}


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__.strip().splitlines()[2], file=sys.stderr)
        return 2
    root = Path(sys.argv[1]).resolve()
    dest_root = Path(sys.argv[2])
    targets = sys.argv[3:] or sorted(SEEDERS)
    unknown = [target for target in targets if target not in SEEDERS]
    if unknown:
        print(f"unknown fuzz targets: {', '.join(unknown)}", file=sys.stderr)
        return 2
    for target in targets:
        destination = dest_root / target
        destination.mkdir(parents=True, exist_ok=True)
        SEEDERS[target](root, destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
