use crate::{
    ast::{SourceBpm, SourceLiteral},
    version::Version,
};

#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Token {
    Header(Version),
    Semver(Version),
    InvalidVersion,
    UnsupportedVersion,
    InvalidSemver,
    InvalidNumeric,
    NonFiniteNumeric,
    InvalidColor,
    InvalidLexeme,
    ResourceLimit {
        kind: &'static str,
        limit: usize,
        observed: usize,
    },
    TempoBpm(SourceBpm),
    Literal(SourceLiteral),
    Identifier(String),
    Keyword(Keyword),
    Punctuation(Punctuation),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Keyword {
    Format,
    Profile,
    Features,
    Fragment,
    Chart,
    Playable,
    Renderable,
    Publishable,
    Meta,
    Contributors,
    Person,
    Credits,
    Credit,
    Resources,
    Artwork,
    Sync,
    Definitions,
    Const,
    Let,
    Fn,
    Template,
    Return,
    If,
    Else,
    Choose,
    When,
    Generate,
    Emit,
    In,
    Step,
    With,
    Null,
    TempoMap,
    Lines,
    Line,
    LineType,
    Collections,
    Notes,
    Judgelines,
    Tracks,
    Track,
    Segments,
    Segment,
    Keyframe,
    KeyframeType,
    Point,
    Using,
    ScrollTempoMap,
    CubicBezier,
    Render,
    Extensions,
    Extension,
    Required,
    Optional,
    Preserve,
    Source,
    Payload,
    Audio,
    Image,
    Font,
    Texture,
    Path,
    Shader,
    Binary,
    Bool,
    Int,
    Float,
    String,
    Time,
    Beat,
    Length,
    Angle,
    Color,
    Vec2,
    Array,
    Note,
    RenderNode,
    TrackType,
    TrackSegment,
    Tap,
    Hold,
    Flick,
    Drag,
}

impl Keyword {
    pub(crate) fn from_identifier(identifier: &str) -> Option<Self> {
        Some(match identifier {
            "format" => Self::Format,
            "profile" => Self::Profile,
            "features" => Self::Features,
            "fragment" => Self::Fragment,
            "chart" => Self::Chart,
            "playable" => Self::Playable,
            "renderable" => Self::Renderable,
            "publishable" => Self::Publishable,
            "meta" => Self::Meta,
            "contributors" => Self::Contributors,
            "person" => Self::Person,
            "credits" => Self::Credits,
            "credit" => Self::Credit,
            "resources" => Self::Resources,
            "artwork" => Self::Artwork,
            "sync" => Self::Sync,
            "definitions" => Self::Definitions,
            "const" => Self::Const,
            "let" => Self::Let,
            "fn" => Self::Fn,
            "template" => Self::Template,
            "return" => Self::Return,
            "if" => Self::If,
            "else" => Self::Else,
            "choose" => Self::Choose,
            "when" => Self::When,
            "generate" => Self::Generate,
            "emit" => Self::Emit,
            "in" => Self::In,
            "step" => Self::Step,
            "with" => Self::With,
            "null" => Self::Null,
            "tempoMap" => Self::TempoMap,
            "lines" => Self::Lines,
            "line" => Self::Line,
            "collections" => Self::Collections,
            "notes" => Self::Notes,
            "judgelines" => Self::Judgelines,
            "tracks" => Self::Tracks,
            "track" => Self::Track,
            "segments" => Self::Segments,
            "segment" => Self::Segment,
            "keyframe" => Self::Keyframe,
            "point" => Self::Point,
            "using" => Self::Using,
            "scrollTempoMap" => Self::ScrollTempoMap,
            "cubicBezier" => Self::CubicBezier,
            "render" => Self::Render,
            "extensions" => Self::Extensions,
            "extension" => Self::Extension,
            "required" => Self::Required,
            "optional" => Self::Optional,
            "preserve" => Self::Preserve,
            "source" => Self::Source,
            "payload" => Self::Payload,
            "audio" => Self::Audio,
            "image" => Self::Image,
            "font" => Self::Font,
            "texture" => Self::Texture,
            "path" => Self::Path,
            "shader" => Self::Shader,
            "binary" => Self::Binary,
            "bool" => Self::Bool,
            "int" => Self::Int,
            "float" => Self::Float,
            "string" => Self::String,
            "time" => Self::Time,
            "beat" => Self::Beat,
            "length" => Self::Length,
            "angle" => Self::Angle,
            "color" => Self::Color,
            "vec2" => Self::Vec2,
            "array" => Self::Array,
            "Note" => Self::Note,
            "Line" => Self::LineType,
            "RenderNode" => Self::RenderNode,
            "Track" => Self::TrackType,
            "TrackSegment" => Self::TrackSegment,
            "Keyframe" => Self::KeyframeType,
            "tap" => Self::Tap,
            "hold" => Self::Hold,
            "flick" => Self::Flick,
            "drag" => Self::Drag,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Punctuation {
    LeftParenthesis,
    RightParenthesis,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Comma,
    Colon,
    Semicolon,
    Dot,
    At,
    Arrow,
    FatArrow,
    RangeExclusive,
    RangeInclusive,
    Plus,
    Minus,
    Star,
    Power,
    Slash,
    Percent,
    Bang,
    Equal,
    EqualEqual,
    BangEqual,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
    AndAnd,
    OrOr,
}
