use crate::{
    ast::{Bpm, SourceLiteral},
    version::Version,
};

#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Token {
    Header(Version),
    InvalidVersion,
    UnsupportedVersion,
    TempoBpm(Bpm),
    Literal(SourceLiteral),
    Identifier(String),
    Keyword(Keyword),
    Punctuation(Punctuation),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Keyword {
    Format,
    Fragment,
    Chart,
    Playable,
    Renderable,
    Publishable,
    Meta,
    Contributors,
    Credits,
    Resources,
    Artwork,
    Sync,
    Custom,
    Definitions,
    Const,
    Let,
    Fn,
    Template,
    Return,
    If,
    Else,
    Choose,
    When,
    Generate,
    Emit,
    In,
    Step,
    With,
    Null,
    Lines,
    Line,
    LineType,
    Collections,
    Notes,
    Judgelines,
    Tracks,
    Track,
    Segments,
    Segment,
    Keyframe,
    KeyframeType,
    Point,
    Using,
    Render,
    Extensions,
    Preserve,
    Bool,
    Int,
    Float,
    String,
    Time,
    Beat,
    Length,
    Angle,
    Color,
    Vec2,
    Array,
    Note,
    RenderNode,
    TrackType,
    TrackSegment,
    Tap,
    Hold,
    Flick,
    Drag,
    Above,
    Below,
    Replace,
    Add,
    Multiply,
    Base,
    Zero,
    One,
    Error,
    HoldBefore,
    HoldAfter,
}

impl Keyword {
    pub(crate) fn from_identifier(identifier: &str) -> Option<Self> {
        Some(match identifier {
            "format" => Self::Format,
            "fragment" => Self::Fragment,
            "chart" => Self::Chart,
            "playable" => Self::Playable,
            "renderable" => Self::Renderable,
            "publishable" => Self::Publishable,
            "meta" => Self::Meta,
            "contributors" => Self::Contributors,
            "credits" => Self::Credits,
            "resources" => Self::Resources,
            "artwork" => Self::Artwork,
            "sync" => Self::Sync,
            "custom" => Self::Custom,
            "definitions" => Self::Definitions,
            "const" => Self::Const,
            "let" => Self::Let,
            "fn" => Self::Fn,
            "template" => Self::Template,
            "return" => Self::Return,
            "if" => Self::If,
            "else" => Self::Else,
            "choose" => Self::Choose,
            "when" => Self::When,
            "generate" => Self::Generate,
            "emit" => Self::Emit,
            "in" => Self::In,
            "step" => Self::Step,
            "with" => Self::With,
            "null" => Self::Null,
            "lines" => Self::Lines,
            "line" => Self::Line,
            "collections" => Self::Collections,
            "notes" => Self::Notes,
            "judgelines" => Self::Judgelines,
            "tracks" => Self::Tracks,
            "track" => Self::Track,
            "segments" => Self::Segments,
            "segment" => Self::Segment,
            "keyframe" => Self::Keyframe,
            "point" => Self::Point,
            "using" => Self::Using,
            "render" => Self::Render,
            "extensions" => Self::Extensions,
            "preserve" => Self::Preserve,
            "bool" => Self::Bool,
            "int" => Self::Int,
            "float" => Self::Float,
            "string" => Self::String,
            "time" => Self::Time,
            "beat" => Self::Beat,
            "length" => Self::Length,
            "angle" => Self::Angle,
            "color" => Self::Color,
            "vec2" => Self::Vec2,
            "array" => Self::Array,
            "Note" => Self::Note,
            "Line" => Self::LineType,
            "RenderNode" => Self::RenderNode,
            "Track" => Self::TrackType,
            "TrackSegment" => Self::TrackSegment,
            "Keyframe" => Self::KeyframeType,
            "tap" => Self::Tap,
            "hold" => Self::Hold,
            "flick" => Self::Flick,
            "drag" => Self::Drag,
            "above" => Self::Above,
            "below" => Self::Below,
            "replace" => Self::Replace,
            "add" => Self::Add,
            "multiply" => Self::Multiply,
            "base" => Self::Base,
            "zero" => Self::Zero,
            "one" => Self::One,
            "error" => Self::Error,
            "holdBefore" => Self::HoldBefore,
            "holdAfter" => Self::HoldAfter,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Punctuation {
    LeftParenthesis,
    RightParenthesis,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Comma,
    Colon,
    Semicolon,
    Dot,
    At,
    Arrow,
    FatArrow,
    RangeExclusive,
    RangeInclusive,
    Plus,
    Minus,
    Star,
    Power,
    Slash,
    Percent,
    Bang,
    Equal,
    EqualEqual,
    BangEqual,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
    AndAnd,
    OrOr,
}
