use crate::{
    ast::{SourceBpm, SourceLiteral},
    version::Version,
};

#[derive(Debug, Clone, PartialEq)]
pub(crate) enum Token {
    Header(Version),
    Semver(Version),
    InvalidVersion,
    UnsupportedVersion,
    InvalidSemver,
    InvalidNumeric,
    NonFiniteNumeric,
    InvalidColor,
    InvalidLexeme,
    ResourceLimit {
        kind: &'static str,
        limit: usize,
        observed: usize,
    },
    TempoBpm(SourceBpm),
    Literal(SourceLiteral),
    Identifier(String),
    Keyword(Keyword),
    Punctuation(Punctuation),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Keyword {
    Format,
    Profile,
    Features,
    Fragment,
    Chart,
    Playable,
    Renderable,
    Publishable,
    Meta,
    Contributors,
    Person,
    Credits,
    Credit,
    Resources,
    Artwork,
    Sync,
    Definitions,
    Const,
    Let,
    Fn,
    Template,
    Return,
    If,
    Else,
    Choose,
    When,
    Generate,
    Emit,
    In,
    Step,
    With,
    Null,
    TempoMap,
    Lines,
    Line,
    LineType,
    Collections,
    Notes,
    Judgelines,
    Tracks,
    Track,
    Segments,
    Segment,
    Keyframe,
    KeyframeType,
    Point,
    Using,
    ScrollTempoMap,
    CubicBezier,
    Render,
    Extensions,
    Extension,
    Required,
    Optional,
    Preserve,
    Source,
    Payload,
    Audio,
    Image,
    Font,
    Texture,
    Path,
    Shader,
    Binary,
    Bool,
    Int,
    Float,
    String,
    Time,
    Beat,
    Length,
    Angle,
    Color,
    Vec2,
    Array,
    Note,
    RenderNode,
    TrackType,
    TrackSegment,
    Tap,
    Hold,
    Flick,
    Drag,
}

impl Keyword {
    pub(crate) fn from_identifier(identifier: &str) -> Option<Self> {
        Some(match identifier {
            "format" => Self::Format,
            "profile" => Self::Profile,
            "features" => Self::Features,
            "fragment" => Self::Fragment,
            "chart" => Self::Chart,
            "playable" => Self::Playable,
            "renderable" => Self::Renderable,
            "publishable" => Self::Publishable,
            "meta" => Self::Meta,
            "contributors" => Self::Contributors,
            "person" => Self::Person,
            "credits" => Self::Credits,
            "credit" => Self::Credit,
            "resources" => Self::Resources,
            "artwork" => Self::Artwork,
            "sync" => Self::Sync,
            "definitions" => Self::Definitions,
            "const" => Self::Const,
            "let" => Self::Let,
            "fn" => Self::Fn,
            "template" => Self::Template,
            "return" => Self::Return,
            "if" => Self::If,
            "else" => Self::Else,
            "choose" => Self::Choose,
            "when" => Self::When,
            "generate" => Self::Generate,
            "emit" => Self::Emit,
            "in" => Self::In,
            "step" => Self::Step,
            "with" => Self::With,
            "null" => Self::Null,
            "tempoMap" => Self::TempoMap,
            "lines" => Self::Lines,
            "line" => Self::Line,
            "collections" => Self::Collections,
            "notes" => Self::Notes,
            "judgelines" => Self::Judgelines,
            "tracks" => Self::Tracks,
            "track" => Self::Track,
            "segments" => Self::Segments,
            "segment" => Self::Segment,
            "keyframe" => Self::Keyframe,
            "point" => Self::Point,
            "using" => Self::Using,
            "scrollTempoMap" => Self::ScrollTempoMap,
            "cubicBezier" => Self::CubicBezier,
            "render" => Self::Render,
            "extensions" => Self::Extensions,
            "extension" => Self::Extension,
            "required" => Self::Required,
            "optional" => Self::Optional,
            "preserve" => Self::Preserve,
            "source" => Self::Source,
            "payload" => Self::Payload,
            "audio" => Self::Audio,
            "image" => Self::Image,
            "font" => Self::Font,
            "texture" => Self::Texture,
            "path" => Self::Path,
            "shader" => Self::Shader,
            "binary" => Self::Binary,
            "bool" => Self::Bool,
            "int" => Self::Int,
            "float" => Self::Float,
            "string" => Self::String,
            "time" => Self::Time,
            "beat" => Self::Beat,
            "length" => Self::Length,
            "angle" => Self::Angle,
            "color" => Self::Color,
            "vec2" => Self::Vec2,
            "array" => Self::Array,
            "Note" => Self::Note,
            "Line" => Self::LineType,
            "RenderNode" => Self::RenderNode,
            "Track" => Self::TrackType,
            "TrackSegment" => Self::TrackSegment,
            "Keyframe" => Self::KeyframeType,
            "tap" => Self::Tap,
            "hold" => Self::Hold,
            "flick" => Self::Flick,
            "drag" => Self::Drag,
            _ => return None,
        })
    }

    pub(crate) const fn as_str(self) -> &'static str {
        match self {
            Self::Format => "format",
            Self::Profile => "profile",
            Self::Features => "features",
            Self::Fragment => "fragment",
            Self::Chart => "chart",
            Self::Playable => "playable",
            Self::Renderable => "renderable",
            Self::Publishable => "publishable",
            Self::Meta => "meta",
            Self::Contributors => "contributors",
            Self::Person => "person",
            Self::Credits => "credits",
            Self::Credit => "credit",
            Self::Resources => "resources",
            Self::Artwork => "artwork",
            Self::Sync => "sync",
            Self::Definitions => "definitions",
            Self::Const => "const",
            Self::Let => "let",
            Self::Fn => "fn",
            Self::Template => "template",
            Self::Return => "return",
            Self::If => "if",
            Self::Else => "else",
            Self::Choose => "choose",
            Self::When => "when",
            Self::Generate => "generate",
            Self::Emit => "emit",
            Self::In => "in",
            Self::Step => "step",
            Self::With => "with",
            Self::Null => "null",
            Self::TempoMap => "tempoMap",
            Self::Lines => "lines",
            Self::Line => "line",
            Self::Collections => "collections",
            Self::Notes => "notes",
            Self::Judgelines => "judgelines",
            Self::Tracks => "tracks",
            Self::Track => "track",
            Self::Segments => "segments",
            Self::Segment => "segment",
            Self::Keyframe => "keyframe",
            Self::Point => "point",
            Self::Using => "using",
            Self::ScrollTempoMap => "scrollTempoMap",
            Self::CubicBezier => "cubicBezier",
            Self::Render => "render",
            Self::Extensions => "extensions",
            Self::Extension => "extension",
            Self::Required => "required",
            Self::Optional => "optional",
            Self::Preserve => "preserve",
            Self::Source => "source",
            Self::Payload => "payload",
            Self::Audio => "audio",
            Self::Image => "image",
            Self::Font => "font",
            Self::Texture => "texture",
            Self::Path => "path",
            Self::Shader => "shader",
            Self::Binary => "binary",
            Self::Bool => "bool",
            Self::Int => "int",
            Self::Float => "float",
            Self::String => "string",
            Self::Time => "time",
            Self::Beat => "beat",
            Self::Length => "length",
            Self::Angle => "angle",
            Self::Color => "color",
            Self::Vec2 => "vec2",
            Self::Array => "array",
            Self::Note => "Note",
            Self::LineType => "Line",
            Self::RenderNode => "RenderNode",
            Self::TrackType => "Track",
            Self::TrackSegment => "TrackSegment",
            Self::KeyframeType => "Keyframe",
            Self::Tap => "tap",
            Self::Hold => "hold",
            Self::Flick => "flick",
            Self::Drag => "drag",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Punctuation {
    LeftParenthesis,
    RightParenthesis,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Comma,
    Colon,
    Semicolon,
    Dot,
    At,
    Arrow,
    FatArrow,
    RangeExclusive,
    RangeInclusive,
    Plus,
    Minus,
    Star,
    Power,
    Slash,
    Percent,
    Bang,
    Equal,
    EqualEqual,
    BangEqual,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
    AndAnd,
    OrOr,
}
